{
 "title": "Energy Stats - Consumer details",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Airco kWh",
   "type": "stat",
   "description": "Total Energy consumption Airco over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Airco consumption (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"airco-zolder-en-slaapkamer_mean\") / 60000 as azs_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zolder Verlichting kWh",
   "type": "stat",
   "description": "Total Energy consumption Verlichting Zolder over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Airco consumption (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"zolder-verlichting_mean\") / 60000 as zv_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zolder Stopkontakten kWh",
   "type": "stat",
   "description": "Total Energy consumption Stopkontakten Zolder over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Zolder stopkontakten (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT (sum(\"zolder-stopkontakten-network-switch_mean\") + sum(\"zolder-stopkontakten-printer_mean\") + sum(\"zolder-bureau_mean\")) / 60000 as zsp_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stopkontakten Bureau kWh",
   "type": "stat",
   "description": "Total Energy consumption Stopkontakten Bureau over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Stopkontakten Bureau consumption (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"zolder-bureau_mean\") / 60000 as zsp_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gelijkvloers stopkontakten kWh",
   "type": "stat",
   "description": "Total Energy consumption Stopkontakten Gelijkvloers over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Stopkontakten gelijkvloers consumption (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"gelijkvloers-stopkontakten_mean\") / 60000 as azs_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Stopkontakten 1ste verdieping kWh",
   "type": "stat",
   "description": "Total Energy consumption stopkontakten 1ste verdieping over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Stopkontakten 1ste verdieping (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"verdieping-1-stopkontakten_mean\") / 60000 as azs_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vaatwasser kWh",
   "type": "stat",
   "description": "Total Energy consumption Vaatwasser over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Vaatwasser total energy consumption (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"vaatwasser_mean\") / 60000 as azs_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fornuis kWh",
   "type": "stat",
   "description": "Total Energy consumption Fornuis over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Fornuis energy consumption Fornuis (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"fornuis_mean\") / 60000 as zsp_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Oven kWh",
   "type": "stat",
   "description": "Total Energy consumption Oven over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Airco consumption (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"oven_mean\") / 60000 as azs_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total tuinhuis-fietsgarage kWh",
   "type": "stat",
   "description": "Total Energy consumption Tuinhuis-Fietsgarage over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Airco consumption (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"tuinhuis-fietsgarage_mean\") / 60000 as zsp_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Garage kWh",
   "type": "stat",
   "description": "Total Energy consumption Garage over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Garage (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT sum(\"garage_mean\") / 60000 as azs_sum FROM \"smappee-data-2\" WHERE $timeFilter\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage main Min/Max",
   "type": "stat",
   "description": "Mains voltage minimal and maximal value in selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT min(voltage_mean_values) as Min from (SELECT \"voltage_mean\" as voltage_mean_values FROM \"smappee-data-2\") WHERE $timeFilter GROUP BY time(8760h) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Max",
     "query": "SELECT max(voltage_mean_values)  as Max from (SELECT \"voltage_mean\" as voltage_mean_values FROM \"smappee-data-2\") WHERE $timeFilter GROUP BY time(8760h) fill(null)"
    }
   ]
  },
  {
   "title": "Zolder - verlichting",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "Zolder - verlichting (bureaulamp, plafondspots, plafondlamp utility room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "zolder-verlichting_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Tuinhuis & fietsgarage",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "Tuinhuis verlichting & stopkontakten / fietsgarage stopkontakt",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "tuinhuis-fietsgarage_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Gelijkvloers stopkontakten",
   "type": "timeseries",
   "description": "Totaal stopcontacten gelijkvloers",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Gelijkvloers stopkontakten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"gelijkvloers-stopkontakten_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "1ste verdieping stopkontakten",
   "type": "timeseries",
   "description": "Vermogen alle stopkontakten 1ste verdieping",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "alias": "1ste verdieping stopkontakten",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"verdieping-1-stopkontakten_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zolder - stopkontakten",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "Stopkontakten - netwerkswitch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       {
        "params": [
         "zolder-stopkontakten-network-switch_mean"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Stopkontakten + printer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       {
        "params": [
         "zolder-stopkontakten-printer_mean"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zolder - stopkontakten bureau",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "alias": "Solar Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"solar_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Zolder - stopkontakten bureau",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "zolder-bureau_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Airco - zolder & slaapkamer",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "alias": "Solar Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"solar_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Airco - zolder & slaapkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       {
        "params": [
         "airco-zolder-en-slaapkamer_mean"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Zolder - totaal zekeringskast",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "alias": "Solar Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"solar_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Zolder - totaal zekeringskast",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "zolder-zekeringkast_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Vaatwasser",
   "type": "timeseries",
   "description": "Vaatwasser",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "alias": "Vaatwasser",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"vaatwasser_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fornuis",
   "type": "timeseries",
   "description": "Fornuis",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "alias": "Fornuis",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"fornuis_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Garage",
   "type": "timeseries",
   "description": "Garage",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "alias": "Garage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"garage_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Oven",
   "type": "timeseries",
   "description": "Elektrische oven",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "alias": "Oven",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "query": "SELECT mean(\"oven_mean\") FROM \"smappee-data-2\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mains Frequency",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "alias": "Netfrequentie",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "measuredFrequency_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mains Voltage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 104 },
   "targets": [
    {
     "alias": "Mains voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "voltage_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatuur",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "alias": "Zolder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-zolder"
      }
     ]
    },
    {
     "alias": "Badkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-badkamer"
      }
     ]
    },
    {
     "alias": "Woonkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-woonkamer"
      }
     ]
    },
    {
     "alias": "Slaapkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-slaapkamer"
      }
     ]
    },
    {
     "alias": "Tuinhok",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-buiten-tuinhok"
      }
     ]
    }
   ]
  },
  {
   "title": "Luchtvochtigheid",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "alias": "Zolder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-zolder"
      }
     ]
    },
    {
     "alias": "Badkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-badkamer"
      }
     ]
    },
    {
     "alias": "Woonkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-woonkamer"
      }
     ]
    },
    {
     "alias": "Slaapkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-slaapkamer"
      }
     ]
    },
    {
     "alias": "Tuinhok",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-buiten-tuinhok"
      }
     ]
    }
   ]
  }
 ]
}