{
 "title": "Energy Stats - Consumption and production",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Total Solar kWh",
   "type": "stat",
   "description": "Total Solar Energy production over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total solar production (kWh)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT sum(\"solar_mean\") / 1000 / 60 as solar_mean_sum FROM \"smappee-data-test\" where $timeFilter and \"solar_mean\" > 0",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar kW",
   "type": "stat",
   "description": "Current solar power output",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Solar power output (KW)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT last(\"solar_mean\") / 1000 FROM \"smappee-data-test\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Consumption kWh",
   "type": "stat",
   "description": "Total Energy consumption over selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total KWh Consumption",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT sum(\"consumption_mean\") / 60000 as consumption_mean_sum FROM \"smappee-data-test\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Consumption kW",
   "type": "stat",
   "description": "Current Energy consumption",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Current power consumption (kW)",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT last(\"consumption_mean\") / 1000 FROM \"smappee-data-test\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Voltage main Min/Max",
   "type": "stat",
   "description": "Mains voltage minimal and maximal value in selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT min(voltage_mean_values) as Min from (SELECT \"voltage_mean\" as voltage_mean_values FROM \"smappee-data-test\") WHERE $timeFilter GROUP BY time(8760h) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Max",
     "query": "SELECT max(voltage_mean_values)  as Max from (SELECT \"voltage_mean\" as voltage_mean_values FROM \"smappee-data-test\") WHERE $timeFilter GROUP BY time(8760h) fill(null)"
    }
   ]
  },
  {
   "title": "Mains Freq",
   "type": "stat",
   "description": "Mains voltage minimal and maximal value in selected time interval",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "measuredFrequency_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Solar Production / Total Consumption",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "alias": "Solar Production",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT mean(\"solar_mean\") FROM \"smappee-data-test\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Consumption",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "select": [
      [
       { "params": [ "consumption_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power budget",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "alias": "Power budget",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT (mean(\"solar_mean\") - mean(\"consumption_mean\") + abs(mean(\"consumption_mean\") - mean(\"solar_mean\")))/2 FROM \"smappee-data-test\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Power import",
   "type": "timeseries",
   "description": "Solar production & consumption by minute averages",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "alias": "Power import",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "query": "SELECT (mean(\"consumption_mean\") - mean(\"solar_mean\") + abs(mean(\"consumption_mean\") - mean(\"solar_mean\")))/2 FROM \"smappee-data-test\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "solar_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mains Voltage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "alias": "Mains voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-test",
     "select": [
      [
       { "params": [ "voltage_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatuur",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "alias": "Zolder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-zolder"
      }
     ]
    },
    {
     "alias": "Badkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-badkamer"
      }
     ]
    },
    {
     "alias": "Woonkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-woonkamer"
      }
     ]
    },
    {
     "alias": "Slaapkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-slaapkamer"
      }
     ]
    },
    {
     "alias": "Tuinhok",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-buiten-tuinhok"
      }
     ]
    }
   ]
  },
  {
   "title": "Luchtvochtigheid",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "alias": "Zolder",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-zolder"
      }
     ]
    },
    {
     "alias": "Badkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-badkamer"
      }
     ]
    },
    {
     "alias": "Woonkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-woonkamer"
      }
     ]
    },
    {
     "alias": "Slaapkamer",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-slaapkamer"
      }
     ]
    },
    {
     "alias": "Tuinhok",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zigbee_mqtt",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      {
       "key": "topic",
       "operator": "=",
       "value": "temp-hum/temperatuur-luchtvochtigheid-buiten-tuinhok"
      }
     ]
    }
   ]
  },
  {
   "title": "Mains Frequency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {
     "alias": "Mains voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "smappee-data-2",
     "select": [
      [
       { "params": [ "measuredFrequency_mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}